### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by darkdragon-001** [mregmi/ext2read#6]
Can somebody please elaborate on the building environment?

I downloaded Qt 5.8.0 and used Qt Creator with Visual Studio 2015 compiler on Windows 10, but `dirent.h` was not found. Therefore, I suggest another compiler must be used. Which compiler works?

@mregmi Do you use MinGW or GCC (cross-compiling)? Or something else?

**Comment by darkdragon-001** [comment]
I managed to build and run the project for both 32bit and 64bit.

First, some deprecated functions had to be changed (`QString::fromAscii()` and `QString::toAscii()`). I changed them to use `QString::fromUtf8()` and `QString::toUtf8()`.

# 32bit

I used the official [Qt 5.8.0 for Windows 32-bit (MinGW 5.3.0, 1.2 GB) which includes Qt-Creator 4.2.1](https://www.qt.io/download-open-source/#section-2). 

# 64bit

I used [MinGW-W64 (7.1.0 posix-seh)](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/) and [Qt64-NG (5.5.0 posix-seh)](https://sourceforge.net/projects/qt64ng/files/qt/x86-64/) and [Qt-Creator (4.2.2)](https://www.qt.io/download-open-source/#section-2). [This tutorial (see section _Install and configuration_)](http://stackoverflow.com/a/38547137/3779655) explains the process of setting up the toolchain.

# FAQ

Running the application results in the following error:

    The application was unable to start correctly (0xc000007b). Click OK to close the application.

This error means that the bitness (32, 64 Bit) of application and DLLs do not correspond.

The easiest fix is to copy the Qt dependencies in the same path as the EXE file.

Another approach is to setup your environment correclty. Make sure you have Qt with the correct bitness on top (since other software might include old Qt DLLs with wrong bitness) of `PATH` environment variable. You can check the resolved dependencies e.g. with [this tool](http://www.dependencywalker.com/).

**Comment by mregmi** [comment]
Awesome thanks for fixing it.
